# Generated by Django 3.1.5 on 2021-01-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_book_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_details',
            name='purchase_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='book_details',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
