# Generated by Django 3.1.5 on 2021-02-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookDonation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('mobile', models.IntegerField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('pincode', models.IntegerField(blank=True)),
                ('bookname', models.CharField(blank=True, max_length=200)),
                ('authorname', models.CharField(blank=True, max_length=200)),
                ('genre', models.CharField(blank=True, max_length=200)),
                ('img', models.ImageField(blank=True, upload_to='donate/%Y/%m/%d/')),
            ],
        ),
    ]
